name: C Language CI

on:
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up C compiler Linux
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y gcc

    - name: Set up C compiler on macOS
      if: matrix.os == 'macos-latest'
      run: brew install gcc

    - name: Build and Test
      run: |
        make
        ./philosophers

  norminette:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Python and Norminette
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        pip3 install norminette

    - name: Run Norminette
      run: |
        LINE_COUNT=$(make norm | wc -l)
        if [ "LINE_COUNT" -ne 6 ]; then
          exit 1
        else
          echo OK
        fi
          
